route:
  group_by: ['alertname', 'job']
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5s
  receiver: discord

receivers:
  - name: discord
    discord_configs:
      - webhook_url: 'https://discord.com/api/webhooks/1372423486802231338/VQwyn9JKv9CL73zrjx923hDabLrAp42IyNB13BLv6u0tqcYH-psMtkQyxJc0yBydf7lJ'
