global:
  scrape_interval: 15s

rule_files:
  - "alerting_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['192.168.18.118:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.18.118:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.18.118:9100']

